[package]
name = "commrate"
version = "0.1.0"
authors = ["Danila Kiver <danila.kiver@mail.ru>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
colored = "1.8.0"
enumset = "1.0.11"
git2 = { version = "0.10.1", default-features = false }
lazy_static = "1.4.0"
libc = "0.2.62"
regex = "1.3.1"
